--TODO: fix audit tables (need to embed all fields from base tables)
--TODO: switch IDs from SERIAL to IDENTITY
--TODO: make shipping 0 for order over 100 EUR
--TODO: increase shipping for heavier stuff
--TODO: figure out how to do discounts
--TODO: if order has shipped, add tracking number
--TODO: make add_product return productid
--TODO: copy functions from eshop-operations.sql to here
--TODO: remove productonsale
--TODO: remove userbecameadmin
--TODO: simplify manufacturer to have addressid

