/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angle
 */

import java.io.*;
import java.util.*;
//import javax.swing.*;

public class inherewriter extends javax.swing.JFrame {

    /**
     * Creates new form inherewriter
     */
    public inherewriter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ddifTextField = new javax.swing.JTextField();
        ddofTextField = new javax.swing.JTextField();
        ddofLabel = new javax.swing.JLabel();
        ddifLabel = new javax.swing.JLabel();
        writeButton = new javax.swing.JButton();

        label1.setText("label1");

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("inherewriter");

        ddifTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ddifTextField.setText("/home/angle/ref");
        ddifTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddifTextFieldActionPerformed(evt);
            }
        });

        ddofTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ddofTextField.setText("/home/angle/ddof");

        ddofLabel.setText("device to write");

        ddifLabel.setText("path to iso");

        writeButton.setText("write");
        writeButton.setAlignmentX(0.5F);
        writeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(writeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddofTextField)
                    .addComponent(ddifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddifLabel)
                    .addComponent(ddofLabel))
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ddifTextField, ddofTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddifLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddofTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddofLabel))
                .addGap(18, 18, 18)
                .addComponent(writeButton)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ddifTextField, ddofTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddifTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddifTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddifTextFieldActionPerformed

    private void writeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeButtonActionPerformed
        // TODO add your handling code here:
        
            String[] command = {"/bin/dd", "if=", "of="};
            command[1] = command[1] + ddifTextField.getText();
            command[2] = command[2] + ddofTextField.getText();
            String cdd = "";
            for(int i=0;i<command.length;i++)
                cdd = cdd + command[i] + " ";
            System.out.println("array command tostring: " + Arrays.toString(command));
            System.out.println(cdd);
            try {
            pleaseFuckingWork(cdd);
            }
            catch(IOException ex){}
            
    }//GEN-LAST:event_writeButtonActionPerformed

    public void pleaseFuckingWork(String cdd) throws IOException {
    javax.swing.JFrame f = new javax.swing.JFrame();
    String passwd = javax.swing.JOptionPane.showInputDialog(f,"Enter password");
    String[] cmd = {"/bin/bash","-c","echo \"" + passwd + "\" | sudo -S " + cdd};
    System.out.println("array cmd inside method: " + Arrays.toString(cmd));
    Process pb = Runtime.getRuntime().exec(cmd);
    String line;
    BufferedReader input = new BufferedReader(new InputStreamReader(pb.getInputStream()));
    while ((line = input.readLine()) != null) {
        System.out.println(line);
    }
        input.close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inherewriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inherewriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inherewriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inherewriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inherewriter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ddifLabel;
    private javax.swing.JTextField ddifTextField;
    private javax.swing.JLabel ddofLabel;
    private javax.swing.JTextField ddofTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label label1;
    private javax.swing.JButton writeButton;
    // End of variables declaration//GEN-END:variables
}
